#!/bin/bash

NAME="PainelDaBolsa"
DJANGODIR=/paineldabolsa/source
USER=vagrant
GROUP=vagrant
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=server.settings.production

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
# cd $DJANGODIR
# export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
# export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
#RUNDIR=$(dirname $SOCKFILE)
#test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn server.wsgi:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER \
  --group=$GROUP \
  --log-level=debug \
  --bind=0.0.0.0:9000
